sudo: required

services:
  - docker

language: ruby

env:
  matrix:
    - RVM_RUBY_VERSION=2.2
    - RVM_RUBY_VERSION=2.3
    - RVM_RUBY_VERSION=2.4
    - RVM_RUBY_VERSION=2.5
    - RVM_RUBY_VERSION=2.6
    - RVM_RUBY_VERSION=ruby-head

before_install:
- sudo -E rake test:docker:$RVM_RUBY_VERSION:build

script:
- sudo -E rake test:docker:$RVM_RUBY_VERSION
